version: "3"

services:
  server:
    build: .
    container_name: SecureNote-SpringBoot-Server
    environment:
      GIT_CLIENT_ID: $GIT_CLIENT_ID
      GIT_CLIENT_SECRET: $GIT_CLIENT_SECRET
      GOOGLE_CLIENT_ID: $GOOGLE_CLIENT_ID
      GOOGLE_CLIENT_SECRET: GOOGLE_CLIENT_SECRET
      PG_URL: $PG_URL
      PG_PASSWORD: $PG_PASSWORD
      PG_USER: $PG_USER
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: $PG_DB
      POSTGRES_PASSWORD: $PG_PASSWORD
      POSTGRES_USER: $PG_USER
    ports:
      - "5432:5432"


